options:
  port:
    default: 51413
    type: int
    description: Port that Transmission listens on
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging